# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Catppuccin Mocha"
license = "MIT"
description = "A beautiful, warm, and cozy Micro.blog theme using the Catppuccin Mocha color palette. Features dark-first design, excellent accessibility, and clean typography."
homepage = "https://catppuccin.com/palette"
tags = ["blog", "minimal", "dark", "catppuccin", "accessible", "responsive"]
features = ["blog", "dark-theme", "responsive", "accessibility"]
min_version = 0.20

[author]
  name = "j4ck.xyz"
  homepage = "https://j4ck.xyz"

# If porting an existing theme
[original]
  name = "Catppuccin"
  homepage = "https://catppuccin.com/"
  repo = "https://github.com/catppuccin/catppuccin"