# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Catppuccin Mocha"
license = "MIT"
description = "A warm and cozy Micro.blog theme ported from the Catppuccin Mocha color palette"
homepage = "https://github.com/catppuccin/catppuccin"
tags = ["blog", "minimal", "dark", "catppuccin"]
features = ["blog", "dark-theme"]
min_version = 0.20

[author]
  name = "j4ck.xyz"
  homepage = "https://j4ck.xyz"

# If porting an existing theme
[original]
  name = "Catppuccin Mocha"
  homepage = "https://catppuccin.com/palette/"
  repo = "https://github.com/catppuccin/catppuccin"